### ISSUE TITLE
Collapsible block doesn't toggle if the object's metadata "Details" are absent

### ISSUE THREAD

**Issue by mjordan** [Islandora-Labs/islandora_usage_stats_charts#3]
This is not generally a problem except for collection objects, since there is an admin option in the collection solution pack to not show the Details.

**Comment by bondjimbond** [comment]
Collection objects and Scholar objects, if using default configuration.

Collection objects will display correctly if "Display object metadata" is turned on. Scholar (citation, thesis) objects will if "Use standard metadata display" is turned on. If these options aren't chosen, they won't work.

This is because collapse.js is not included (not present in the source) when these options are turned off. Could be a flaw in the the solution packs, but possibly easier to just include collapse.js in this module.

**Comment by mjordan** [comment]
Hmm... it appears that making sure that `collapse.js` is present not the (whole) solution. I'll continue to look into this.

**Comment by mjordan** [comment]
@bondjimbond can you test the issue-3 branch? Appears you need to include both `/misc/collapse.js` and `/misc/form.js` to get that collapsible fieldset to work.

**Comment by bondjimbond** [comment]
That does the job!

**Comment by mjordan** [comment]
Super, I'll merge it in momentarily.

**Comment by mjordan** [comment]
Resolved with 2a93d8f9fd751b28f9da415629397999a8dd0e8b.
